// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using acme_publishing_app.Context;

namespace acme_publishing_app.Migrations
{
    [DbContext(typeof(WebApiContext))]
    [Migration("20230201015046_DBMigration1")]
    partial class DBMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("acme_publishing_app.Models.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = "b00db9eb-7650-4878-b814-8a96d5a8220e",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = "f30e74cd-2494-4fc8-8eb3-8de05c4a821e",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = "070e30e7-488b-47e3-ad28-4379b9be6185",
                            Name = "United States"
                        },
                        new
                        {
                            Id = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19",
                            Name = "South Africa"
                        });
                });

            modelBuilder.Entity("acme_publishing_app.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = "c208fdd5-75d5-4cb9-b202-ed668b77222c",
                            FirstName = "Laura",
                            LastName = "Simmons"
                        },
                        new
                        {
                            Id = "cf994cb1-dc3c-4822-93f7-a7422a016ca9",
                            FirstName = "John",
                            LastName = "Thomas"
                        },
                        new
                        {
                            Id = "d5d4c8e5-c7c1-4e4a-8ba5-49765082f826",
                            FirstName = "David",
                            LastName = "Rogers"
                        });
                });

            modelBuilder.Entity("acme_publishing_app.Models.DeliveryAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CustomerId");

                    b.ToTable("DeliveryAddress");

                    b.HasData(
                        new
                        {
                            Id = "ef813fe9-8ef1-4809-8822-6c9eb5feefea",
                            CountryId = "b00db9eb-7650-4878-b814-8a96d5a8220e",
                            CustomerId = "c208fdd5-75d5-4cb9-b202-ed668b77222c",
                            Description = "Av 10"
                        },
                        new
                        {
                            Id = "f6095b43-57f1-49a7-9acf-ac3d145fef4f",
                            CountryId = "f30e74cd-2494-4fc8-8eb3-8de05c4a821e",
                            CustomerId = "c208fdd5-75d5-4cb9-b202-ed668b77222c",
                            Description = "Av 20"
                        },
                        new
                        {
                            Id = "fd0e69f0-a1af-4091-b8a4-815a058d927a",
                            CountryId = "070e30e7-488b-47e3-ad28-4379b9be6185",
                            CustomerId = "cf994cb1-dc3c-4822-93f7-a7422a016ca9",
                            Description = "Av 30"
                        },
                        new
                        {
                            Id = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f",
                            CountryId = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f",
                            CustomerId = "cf994cb1-dc3c-4822-93f7-a7422a016ca9",
                            Description = "Av 40"
                        },
                        new
                        {
                            Id = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19",
                            CountryId = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19",
                            CustomerId = "d5d4c8e5-c7c1-4e4a-8ba5-49765082f826",
                            Description = "Av 50"
                        });
                });

            modelBuilder.Entity("acme_publishing_app.Models.DeliveryCompany", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrintDistCompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubscriptionId", "CountryId");

                    b.ToTable("DeliveryCompany");

                    b.HasData(
                        new
                        {
                            SubscriptionId = "50909b94-5134-4392-be80-13bcccd2086c",
                            CountryId = "ef813fe9-8ef1-4809-8822-6c9eb5feefea",
                            PrintDistCompanyId = "e094d643-1e9b-4fe5-a051-e4e7a4753a48"
                        },
                        new
                        {
                            SubscriptionId = "50909b94-5134-4392-be80-13bcccd2086c",
                            CountryId = "f6095b43-57f1-49a7-9acf-ac3d145fef4f",
                            PrintDistCompanyId = "e094d643-1e9b-4fe5-a051-e4e7a4753a48"
                        },
                        new
                        {
                            SubscriptionId = "50909b94-5134-4392-be80-13bcccd2086c",
                            CountryId = "fd0e69f0-a1af-4091-b8a4-815a058d927a",
                            PrintDistCompanyId = "e094d643-1e9b-4fe5-a051-e4e7a4753a48"
                        },
                        new
                        {
                            SubscriptionId = "7a852c93-ca4f-4ab5-84ac-c8b70927506e",
                            CountryId = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f",
                            PrintDistCompanyId = "eeed9a4a-e29f-403c-9437-eb34f45948b4"
                        },
                        new
                        {
                            SubscriptionId = "7caba613-eaa2-4c83-9d47-97b438169f95",
                            CountryId = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19",
                            PrintDistCompanyId = "eeed9a4a-e29f-403c-9437-eb34f45948b4"
                        });
                });

            modelBuilder.Entity("acme_publishing_app.Models.DeliveryOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeliveryAddressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrintDistCompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("PrintDistCompanyId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("DeliveryOrder");

                    b.HasData(
                        new
                        {
                            Id = "100db9eb-7650-4878-b814-8a96d5a82201",
                            DeliveryAddressId = "ef813fe9-8ef1-4809-8822-6c9eb5feefea",
                            PrintDistCompanyId = "e094d643-1e9b-4fe5-a051-e4e7a4753a48",
                            SubscriptionId = "50909b94-5134-4392-be80-13bcccd2086c"
                        },
                        new
                        {
                            Id = "230e74cd-2494-4fc8-8eb3-8de05c4a8212",
                            DeliveryAddressId = "f6095b43-57f1-49a7-9acf-ac3d145fef4f",
                            PrintDistCompanyId = "e094d643-1e9b-4fe5-a051-e4e7a4753a48",
                            SubscriptionId = "50909b94-5134-4392-be80-13bcccd2086c"
                        },
                        new
                        {
                            Id = "370e30e7-488b-47e3-ad28-4379b9be6183",
                            DeliveryAddressId = "fd0e69f0-a1af-4091-b8a4-815a058d927a",
                            PrintDistCompanyId = "e094d643-1e9b-4fe5-a051-e4e7a4753a48",
                            SubscriptionId = "50909b94-5134-4392-be80-13bcccd2086c"
                        },
                        new
                        {
                            Id = "44ca9e4c-2f51-4bfb-8ee0-12efe0db1874",
                            DeliveryAddressId = "74ca9e4c-2f51-4bfb-8ee0-12efe0db187f",
                            PrintDistCompanyId = "eeed9a4a-e29f-403c-9437-eb34f45948b4",
                            SubscriptionId = "7a852c93-ca4f-4ab5-84ac-c8b70927506e"
                        },
                        new
                        {
                            Id = "56d124a9-df5b-4ae8-848d-d15bb33bbd15",
                            DeliveryAddressId = "d6d124a9-df5b-4ae8-848d-d15bb33bbd19",
                            PrintDistCompanyId = "eeed9a4a-e29f-403c-9437-eb34f45948b4",
                            SubscriptionId = "7caba613-eaa2-4c83-9d47-97b438169f95"
                        });
                });

            modelBuilder.Entity("acme_publishing_app.Models.PrintDistCompany", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrintDistCompany");

                    b.HasData(
                        new
                        {
                            Id = "e094d643-1e9b-4fe5-a051-e4e7a4753a48",
                            ApiUrl = "http://printer1/api",
                            Name = "Printer Company 1"
                        },
                        new
                        {
                            Id = "eeed9a4a-e29f-403c-9437-eb34f45948b4",
                            ApiUrl = "http://printer2/api",
                            Name = "Printer Company 2"
                        });
                });

            modelBuilder.Entity("acme_publishing_app.Models.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscription");

                    b.HasData(
                        new
                        {
                            Id = "50909b94-5134-4392-be80-13bcccd2086c",
                            Name = "Magazine 1"
                        },
                        new
                        {
                            Id = "7a852c93-ca4f-4ab5-84ac-c8b70927506e",
                            Name = "Magazine 2"
                        },
                        new
                        {
                            Id = "7caba613-eaa2-4c83-9d47-97b438169f95",
                            Name = "Magazine 3"
                        });
                });

            modelBuilder.Entity("acme_publishing_app.Models.DeliveryAddress", b =>
                {
                    b.HasOne("acme_publishing_app.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("acme_publishing_app.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("acme_publishing_app.Models.DeliveryOrder", b =>
                {
                    b.HasOne("acme_publishing_app.Models.DeliveryAddress", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("acme_publishing_app.Models.PrintDistCompany", "PrintDistCompany")
                        .WithMany()
                        .HasForeignKey("PrintDistCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("acme_publishing_app.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryAddress");

                    b.Navigation("PrintDistCompany");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
